### ISSUE TITLE
Automate DKIM records

### ISSUE THREAD

**Issue by Stretch96** [skyscrapers/terraform-ses#4]
It appears the dkim records can be generated with terraform using the `aws_ses_domain_dkim` resource as described here: https://www.terraform.io/docs/providers/aws/r/ses_domain_dkim.html

I believe this will be a breaking change for anyone using the current version of the module, as if the dkim records were manually generated, terraform may not be able to generate them using the `aws_ses_domain_dkim` resource.

If you're happy with this I can go ahead and open a PR.

**Comment by Stretch96** [comment]
Here's the PR - https://github.com/skyscrapers/terraform-ses/pull/5

**Comment by SamClinckspoor** [comment]
Thanks for the PR.

merged in #5
